fineract:
  datasource:
    core:
      host: localhost
      port: 3306
      schema: tenants
      username: mifos
      password: password
    common:
      protocol: jdbc
      subprotocol: mysql
      driverclass_name: com.mysql.cj.jdbc.Driver

token:
  user:
    access-validity-seconds: 600
    refresh-validity-seconds: 43200
  client:
    access-validity-seconds: 3600
    channel:
      secret: "p1234"

config:
  imu:
    rate-validity-seconds: 300

caching:
  enabled: false


security:
  filter-order: 4

spring:
  resources:
    add-mappings: false
  mvc:
    favicon:
      enabled: false
  jmx:
    enabled: false

server:
  port: 5000


rest:
  authorization:
    enabled: true
    settings:
      - endpoint: "/api/v1/transfer/*/refund"
        authority: "hasAuthority('REFUND')"
      - endpoint: "/api/v1/**"
        authority: "hasAuthority('ALL_FUNCTIONS')"
logging:
  level:
    ROOT: INFO

cloud:
  aws:
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAX32JM37TZOJ5AKFB}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false
  azure:
    enabled: false
    blob:
      connection-string:

payment:
  modes:
    - id: "slcb"
      type: "BATCH"

application:
  bucket-name: paymenthub-ee-dev

tenants: "ibank-usa,ibank-india"

channel-connector:
  url: http://bb-connector-channel.mi
  transfer-path: /channel/transfer

